### PR TITLE
*: add support for writing SSH keys

### PR DESCRIPTION
**Pull request by crawford**

### CODE REVIEW

**Comment by crawford** [comment]
WIP: Still needs to learn how to fetch keys.

**Comment by crawford** [comment]
This should be good to go now. It can fetch and write SSH keys on EC2.

```
core@ip-172-31-4-46 ~ $ ./coreos-metadata -cmdline -ssh-keys core
fetching "http://169.254.169.254/2009-04-04/meta-data/public-ipv4": attempt #1
fetching "http://169.254.169.254/2009-04-04/meta-data/local-ipv4": attempt #1
fetching "http://169.254.169.254/2009-04-04/meta-data/hostname": attempt #1
fetching "http://169.254.169.254/2009-04-04/meta-data/public-keys": attempt #1
fetching "http://169.254.169.254/2009-04-04/meta-data/public-keys/0/openssh-key": attempt #1

core@ip-172-31-4-46 ~ $ cat .ssh/authorized_keys.d/coreos-metadata 
ssh-rsa AAAA... crawford
```

**Comment by marineam** [comment]
Looks ok, what will the interaction be between this and the cloudinit based OEM?

**Comment by crawford** [comment]
This isn't enabled by default, so there is no interaction.

**Comment by marineam** [comment]
What about the interaction when it _is_ enabled :-P

**Comment by crawford** [comment]
Well, then you would get duplicate keys. They would end up in `~core/.ssh/authorized_keys.d/coreos-cloudinit` and `~core/.ssh/authorized_keys.d/coreos-metadata`.

**Comment by marineam** [comment]
ok, seems fine as a start but what is the longer term plan? Should the OEM start always enabling the new service and drop it from the cloudinit goo?

**Comment by marineam** [comment]
anyway, that can be sorted later. LGTM

**Comment by crawford** [comment]
Dropping it from cloudinit is definitely an option (I hadn't much thought about). Ignition is going to enable it on certain platforms where it is supported.

**Pull request merged**
