### PR TITLE
Release 4.4.0

### PR DESCRIPTION
**Pull request by lucab**
Changes:
 * providers: setup network kernel arguments in initrd
 * providers/vmware: support injecting custom network kargs
 * cargo: all dependencies updated

### CODE REVIEW

**Comment by lucab** [comment]
@jlebon I re-triggered one of the Jenkins due to a flake, but the other one seems to be off-path (or at Ieast I can't find it).

**Comment by jlebon** [comment]
LGTM

**Review by ashcrow — APPROVED** [review]
:+1:

**Comment by ashcrow** [comment]
Merging per 2 approvals.

**Comment by lucab** [comment]
Tagged: https://github.com/coreos/afterburn/releases/tag/v4.4.0
Published: https://crates.io/crates/afterburn/4.4.0

**Pull request merged**
