### PR TITLE
main: add initial implementation

### PR DESCRIPTION
**Pull request by crawford**

### CODE REVIEW

**Comment by crawford** [comment]
Currently, there is no retry logic. I was considering baking that into the unit file instead.

**Comment by crawford** [comment]
That's a no-go (get it?). I've added the retry logic.

**Comment by crawford** [comment]
```
Aug 10 17:51:24 localhost coreos-metadata[531]: GET 'http://169.254.169.254/2009-04-04/meta-data/public-ipv4': Attempt 0
Aug 10 17:51:24 localhost coreos-metadata[531]: error: Io(Error { repr: Os(101) })
Aug 10 17:51:24 localhost coreos-metadata[531]: sleeping 100ms
Aug 10 17:51:24 localhost coreos-metadata[531]: GET 'http://169.254.169.254/2009-04-04/meta-data/public-ipv4': Attempt 1
Aug 10 17:51:24 localhost coreos-metadata[531]: error: Io(Error { repr: Os(101) })
Aug 10 17:51:24 localhost coreos-metadata[531]: sleeping 200ms
Aug 10 17:51:24 localhost coreos-metadata[531]: GET 'http://169.254.169.254/2009-04-04/meta-data/public-ipv4': Attempt 2
Aug 10 17:51:24 localhost coreos-metadata[531]: GET 'http://169.254.169.254/2009-04-04/meta-data/local-ipv4': Attempt 0
```

**Comment by crawford** [comment]
Updated with fixes.

**Comment by eyakubovich** [comment]
LGTM

**Comment by crawford** [comment]
Closing in favor of https://github.com/coreos/coreos-metadata/pull/3. Dying inside.

**Pull request closed without merging**
