### PR TITLE
cargo: relax dependencies micro versions 

### PR DESCRIPTION
**Pull request by lucab**
This drops strict requirements on micro versions in order to make
packaging efforts more relaxed.

### CODE REVIEW

**Comment by lucab** [comment]
@ignatenkobrain can you please double-check whether this is in fact less painful for you (i.e. distro maintainers) in general?

**Review by igor-raits — COMMENTED** [review]
Yep, looks better :)

**Comment by igor-raits** [comment]
Btw, 1.x ones can be just ^1

**Comment by lucab** [comment]
Rebased to resolve conflicts.

/cc @jlebon

**Review by jlebon — APPROVED** [review]
LGTM!

**Pull request merged**
