### PR TITLE
providers/azure: fetch hostname from metadata 

### LINKED ISSUE #197: Azure: doesn't set hostname
# Bug #  
Afterburn does not set the hostname on Azure.
## Operating System Version ##  
RHCOS
## Afterburn Version ##  
master
## Environment ##  
Azure

## Expected Behavior ##
`/etc/hostname` contains the machine name defined on Azure
## Actual Behavior ##
no file

## Other Information ##
`curl http://169.254.169.254/metadata/instance/compute/name?api-version=2017-08-01&format=text` gives you the hostname

file location should be `/etc/hostname`

Currently Azure provider returns `None`: 
https://github.com/coreos/afterburn/blob/7db2aff2274ccf7439e4b85d5d944c4f90e807bf/src/providers/azure/mod.rs#L413-L415

### PR DESCRIPTION
**Pull request by lucab**
This implements fetching the machine name from Azure metadata.
 
Ref: https://docs.microsoft.com/en-us/azure/virtual-machines/windows/instance-metadata-service
Fixes #197

### CODE REVIEW

**Comment by lucab** [comment]
WIP: this is based on quick spec reading. I haven't tested it on a real Azure instance.

**Comment by bgilbert** [comment]
Fixes https://github.com/coreos/afterburn/issues/197.

**Comment by lucab** [comment]
Double checked the behavior on a real Azure node (standard B1MS), all good. This is ready for review.

**Review by jlebon — APPROVED** [review]
LGTM!

**Comment by crawford** [comment]
I hadn't started on my implementation yet, so this is perfect. This approach looks good to me. We'll eventually want to move the rest of the functionality over to the metadata service in order to support Azure Stack.

LGTM

**Pull request merged**
