### PR TITLE
Openstack metadata service support

### PR DESCRIPTION
**Pull request by cgonyeo**
This commit adds support for the metadata service in openstack.

Tested in vexxhost.

cc @s-urbaniak

### CODE REVIEW

**Comment by s-urbaniak** [comment]
from my side LGTM :+1:

**Comment by cgonyeo** [comment]
Fixes https://github.com/coreos/bugs/issues/1850

**Review by crawford — CHANGES_REQUESTED** [review]
This needs to expose two different providers: openstack-configdrive and openstack-metadata. It is not possible to determine which one to use at runtime. The user will ultimately need to tell us which one to use.

**Comment by cgonyeo** [comment]
Just pushed changes that splits the provider into the two requested labels.

**Comment by cgonyeo** [comment]
I don't have a way to test the config drive currently, so I just changed this PR to only add support for the openstack metadata service (I dropped @dm0-'s commit from this). At the moment it's all that @s-urbaniak needs. I've also updated the PR's title and description to reflect this.

**Comment by cgonyeo** [comment]
Collapsed if statements into less lines in `internal/providers/openstackMetadata/metadata.go`, as per oob request from @crawford

**Review by crawford — APPROVED** [review]

**Pull request merged**
