### PR TITLE
providers: rework to speed up negative tests

### PR DESCRIPTION
**Pull request by lucab**
This refactors Azure and Packet logic in order to inject a custom client.
This allows speeding up negative tests by skipping retries and
backoff timeouts.

### CODE REVIEW

**Review by zonggen — APPROVED** [review]
LGTM! 
Tested locally, tests finished immediately without waiting for timeouts :+1:

**Review by ashcrow — APPROVED** [review]
LGTM.

**Comment by lucab** [comment]
@ashcrow which bits, specifically? I'm taking notes for further future changes. I'm personally aiming at some basic bare `retry` cases soon.

**Pull request merged**
