### PR TITLE
providers: handle missing fields gracefully

### PR DESCRIPTION
**Pull request by crawford**
Fixes https://github.com/coreos/bugs/issues/1306

### CODE REVIEW

**Comment by crawford** [comment]
Tested on an AWS instance without a public address.

```
$ ./coreos-metadata -cmdline -attributes /dev/stdout
fetching "http://169.254.169.254/2009-04-04/meta-data/instance-id": attempt #1
fetching "http://169.254.169.254/2009-04-04/meta-data/public-ipv4": attempt #1
fetching "http://169.254.169.254/2009-04-04/meta-data/local-ipv4": attempt #1
fetching "http://169.254.169.254/2009-04-04/meta-data/hostname": attempt #1
fetching "http://169.254.169.254/2009-04-04/meta-data/public-keys": attempt #1
fetching "http://169.254.169.254/2009-04-04/meta-data/public-keys/0/openssh-key": attempt #1
COREOS_EC2_INSTANCE_ID=i-7cfbcce9
COREOS_EC2_IPV4_LOCAL=172.31.20.139
COREOS_EC2_HOSTNAME=ip-172-31-20-139.us-west-2.compute.internal
```

**Comment by ajeddeloh** [comment]
LGTM

**Comment by jsierles** [comment]
Still seeing this issue with coreos-metadata 0.6.0 on GCE.

```
core@master-b3-staging ~ $ cat /etc/os-release
NAME=CoreOS
ID=coreos
VERSION=1192.2.0
VERSION_ID=1192.2.0
BUILD_ID=2016-10-21-0026
PRETTY_NAME="CoreOS 1192.2.0 (MoreOS)"
ANSI_COLOR="1;32"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"
core@master-b3-staging ~ $ sudo /bin/coreos-metadata -cmdline -attributes /dev/stdout
fetching "http://metadata.google.internal/computeMetadata/v1/instance/network-interfaces/0/access-configs/0/external-ip": attempt #1
failed to fetch metadata: couldn't parse "" as IP address
```

**Comment by crawford** [comment]
@jsierles come on, Google... They return a 200 despite the resource not existing.

```
curl -H "Metadata-Flavor: Google" http://metadata.google.internal/computeMetadata/v1/instance/network-interfaces/0/access-configs/0/external-ip -v
*   Trying 169.254.169.254...
* TCP_NODELAY set
* Connected to metadata.google.internal (169.254.169.254) port 80 (#0)
> GET /computeMetadata/v1/instance/network-interfaces/0/access-configs/0/external-ip HTTP/1.1
> Host: metadata.google.internal
> User-Agent: curl/7.50.3
> Accept: */*
> Metadata-Flavor: Google
> 
< HTTP/1.1 200 OK
< Metadata-Flavor: Google
< Content-Type: application/text
< ETag: 3c19e4d76229ba8c
< Date: Wed, 09 Nov 2016 19:01:29 GMT
< Server: Metadata Server for VM
< Content-Length: 0
< X-XSS-Protection: 1; mode=block
< X-Frame-Options: SAMEORIGIN
< 
* Curl_http_done: called premature == 0
* Connection #0 to host metadata.google.internal left intact
```

**Comment by crawford** [comment]
This fixes the issue https://github.com/coreos/coreos-metadata/pull/29.

**Pull request merged**
