### PR TITLE
Release 3.1.0

### PR DESCRIPTION
**Pull request by lucab**
coreos-metadata 3.1.0:
 * provider: add boot check-in on azure and packet
 * azure: hardcode fallback for wireserver endpoint
 * providers/packet: minor code cleanup
 * cargo: update most dependencies to latest versions

### CODE REVIEW

**Review by jlebon — APPROVED** [review]
LGTM!

**Comment by imcleod** [comment]
LGTM!

**Review by ashcrow — APPROVED** [review]

**Comment by ashcrow** [comment]
LGTM

**Review by arithx — APPROVED** [review]

**Comment by jlebon** [comment]
So, this needs a final piece here for RHCOS/FCOS, which is the actual systemd unit that will replace the phone home service on CL. Should we include it in this repo?

**Comment by imcleod** [comment]
> So, this needs a final piece here for RHCOS/FCOS, which is the actual systemd unit that will replace the phone home service on CL. Should we include it in this repo?

My ideal case, which may be mis-informed, is that once this update goes in, provided azure is identified as the oem id on the kernel command line, all the needfuls will happen on a *COS system to keep in online in Azure.  Likewise for packet.

If that means including the unit file, then I think my answer is yes.

**Comment by ashcrow** [comment]
> If that means including the unit file, then I think my answer is yes.

I agree.

**Comment by jlebon** [comment]
Yeah, definitely no doubt we need a systemd unit *somewhere*. My question was more about *where*. :) It'd be nice to keep it here, but I'd like to confirm the interactions with CL since we probably don't want to change how check-in works there at this point. (Or do we?)

**Comment by lucab** [comment]
@jlebon I think that the service file could live here (next to the existing one). However I think that right now it is quicker to tag this, add the unit via RPM packaging, test everything and then move the unit to here once everything is confirmed ok. If no objections, I'll proceed with the release.

**Comment by jlebon** [comment]
Sure, WFM!

**Pull request merged**
