### PR TITLE
Release coreos-metadata 3.1.2 to add deprecation notice to crates.io

### PR DESCRIPTION
**Pull request by bgilbert**
I'll push the tag after the PR merges, but I'm not planning to create a GitHub Release.

### CODE REVIEW

**Review by lucab — APPROVED** [review]

**Comment by bgilbert** [comment]
[Published to crates.io](https://crates.io/crates/coreos-metadata).

**Comment by lucab** [comment]
It looks like I didn't pay enough attention, and we ended up plainly skipping `3.1.1`.

**Comment by bgilbert** [comment]
That was intentional.  3.1.2 doesn't include any of the commits from the 3.1.1-alpha period, so I thought it would be better to avoid confusion.

**Comment by lucab** [comment]
I see. It makes sense from git-log point of view; I didn't notice initially and just saw the tag progression gap.

**Pull request merged**
