### PR TITLE
providers/libvirt: add libvirt provider using eth0 as network iface

### PR DESCRIPTION
**Pull request by jforman**
Based on the virtualbox provider, but using eth0 instead.

### CODE REVIEW

**Comment by jforman** [comment]
I'm trying to get the tailor tests to pass, but not quite sure which part of my request is making it fail (even with the reasons provided). Any help greatly appreciated.

**Comment by crawford** [comment]
The scope can't have spaces. I would use "providers/libvirt" in this case. Your commit also needs a description after the title.

The rules can be found here: https://github.com/coreos/coreos-metadata/blob/master/.github/tailor.yaml

**Comment by jforman** [comment]
@crawford Yep, just saw it now. Thanks!

**Comment by jforman** [comment]
Following along to close the loop, this PR has been superseded by PR #81 .

**Pull request closed without merging**
