### PR TITLE
Remove cl-legacy feature

### PR DESCRIPTION
**Pull request by bgilbert**
CoreOS Container Linux will be EOL soon, and Flatcar Container Linux ships a fork of this repo.

cc @pothos, @iaguis, @dongsupark for comments.

### CODE REVIEW

**Comment by pothos** [comment]
Hi,
thanks for asking. If you are willing to keep the legacy feature it made it easier to follow upstream. We are not on your latest `master` currently but that is hopefully to change soon. We have a few minor changes regarding the OEM ID which we could even upstream.
But we have no timeline yet when to switch to the new `AFTERBURN_` naming scheme because it is a breaking change; so if you want the `legacy` feature to be gone soon, you could remove it now as well instead of delaying this decision. I think it's better to share Afterburn, not only because I don't like to resolve git conflicts but because it enables us to contribute upstream.

**Comment by bgilbert** [comment]
I'm not opposed to leaving the existing legacy code in place if it's useful.  In that case it would make sense to upstream the Flatcar-specific changes, since hopefully no other distro will be using legacy mode.  Regarding migrating to `AFTERBURN_`, Afterburn could write both the old and new attributes to different files to avoid the need for a flag day.

On the other hand, we'd like to add support for configuring networking via NetworkManager on cloud platforms that require that (e.g. DigitalOcean and Packet).  It'd be a lot easier to do that if we don't need to abstract over both NetworkManager and networkd.

@lucab, any thoughts?

**Comment by lucab** [comment]
Yes, I think we should come up with a plan to drop the feature soon-ish, as that would simplify code & CI.

https://github.com/coreos/afterburn/pull/322 introduced CLI sub-commands/verbs, so assuming that service units can be auto-updated together with the binary, we can consider isolating the legacy logic under its own `afterburn legacy` scope while pulling out bits that are still common (e.g. hostname handling).

**Comment by ashcrow** [comment]
Needs a rebase.

**Comment by bgilbert** [comment]
Rebased.  We're now 9 months past CL EOL, so it seems like a good time to revisit this.

It appears that [Flatcar's fork](https://github.com/kinvolk/afterburn) isn't tracking upstream, and I'm not aware of any additional upstreaming of compat code.  At this point I'd propose dropping the `cl-legacy` feature to ease maintenance.  We can always revisit the compatibility issue with downstream's participation, though I'd argue that a migration plan should be part of that process.

**Comment by lucab** [comment]
Agreed, I'm also looking forward to drop these parts at this point. I think we are going to end up with a cleaner table to accept any future compat logic, if that materializes at some point.

**Comment by lucab** [comment]
Agreed, I'm also looking forward to drop these parts at this point. I think we are going to end up with a cleaner table to accept any future compat logic, if that materializes at some point.

**Comment by bgilbert** [comment]
(deleted duplicate comment)

**Review by jlebon — APPROVED** [review]
Agreed with all the above. Patch itself LGTM!

**Review by jlebon — APPROVED** [review]
Agreed with all the above. Patch itself LGTM!

**Review by travier — APPROVED** [review]

**Pull request merged**
