### PR TITLE
Release 4.3.3

### PR DESCRIPTION
**Pull request by lucab**
Changes:
  * sshkeys: send structured info to journald
 * ci: test a secondary arch on Travis
 * ci: rust version from 1.39.0 to 1.40.0 
 * makefile: tweak install step
 * providers: add vmware
 * util/cmdline: add helpers for detecting network kargs
 * afterburn: minor cleanups
 * ci: hook up to CoreOS CI

### CODE REVIEW

**Comment by sohankunkerkar** [comment]
LGTM

**Review by jlebon — APPROVED** [review]

**Comment by jlebon** [comment]
(Changelog looks meaty; is that worth a minor bump instead?)

**Comment by lucab** [comment]
@jlebon not a clear cut, I was planning for a minor bump after https://github.com/coreos/afterburn/pull/390.

**Comment by jlebon** [comment]
> @jlebon not a clear cut, I was planning for a minor bump after #390.

Sure, SGTM.

**Comment by lucab** [comment]
Tagged: https://github.com/coreos/afterburn/releases/tag/v4.3.3
Published: https://crates.io/crates/afterburn/4.3.3

**Pull request merged**
